issues:
  exclude-rules:
    - linters: [gosimple]
      path: values/drop_test.go # see the note in the file
      text: "S1005:"

    # go generate introduces these
    - path: expressions/scanner.go
      linters: [deadcode, unused, varcheck]
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - varnamelen
    - godox
    - wsl
    - wrapcheck
    - gomnd
    - gochecknoglobals
    - exhaustive
    - testpackage
    - ireturn
    - godot
    - mnd
    - nonamedreturns
    - funlen
    - gci
    - nlreturn
    - inamedparam
    - lll
    - paralleltest
  fix: true
